### ISSUE TITLE
mvx-game-sc returning empty hashes on calling create_game method

### ISSUE THREAD

**Issue by manwithsteelnerves** [multiversx/mx-contracts-rs#36]
I'm currently testing [mvx-game-sc](https://github.com/multiversx/mx-contracts-rs/tree/main/contracts/mvx-game-sc) smart contract and on approving the transaction from Xportal app, it returns success message but the transaction hashes in response are empty. It just returns empty string array.

May I know how to get the game_id once create game method is called? @mihaicalinluca

**Comment by mihaicalinluca** [comment]
Hi,
I have just pushed an update for this contract providing the new id as return value from the create game endpoint. 
Additionally, you can now find a new view function that you can call to get the game id created (game_settings -> game_id).
