### ISSUE TITLE
Unbond event

### ISSUE THREAD

**Issue by rvignolo** [multiversx/mx-contracts-rs#46]
Hi team!

I think there should be an `unbond_event` such that we can correctly index event data. Is that reasonable to you? Thank you! 

https://github.com/multiversx/mx-contracts-rs/blob/7e6df3d37b2913e8529f8ecebcc45a4700f3505d/contracts/liquid-locking/src/lib.rs#L128

**Comment by dragos-rebegea** [comment]
resolved in #47
